swagger: "2.0"
info:
  title: My API
  description: Unified API for my services
  version: 1.0.0
schemes:
  - https
host: tfm-33iqoznlstilo.apigateway.PROJECT_ID.cloud.goog
x-google-endpoints:
  - name: tfm-33iqoznlstilo.apigateway.PROJECT_ID.cloud.goog
    allowCors: true
paths:
  /authentication/login:
    post:
      operationId: loginOperation
      x-google-backend:
        address: https://authentication-GOOGLE_CLOUD_URL/login
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["POST"]
        allow_headers: ["*"]
        max_age: 3600
  /authentication/validate-token:
    post:
      operationId: validateTokenOperation
      x-google-backend:
        address: https://authentication-GOOGLE_CLOUD_URL/validate-token
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["POST"]
        allow_headers: ["*"]
        max_age: 3600
  /authentication/register:
    post:
      operationId: registerOperation
      x-google-backend:
        address: https://authentication-GOOGLE_CLOUD_URL/register
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["POST"]
        allow_headers: ["*"]
        max_age: 3600
  /authentication/change-password:
    post:
      operationId: changePasswordOperation
      x-google-backend:
        address: https://authentication-GOOGLE_CLOUD_URL/change-password
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["POST"]
        allow_headers: ["*"]
        max_age: 3600
  /health:
    post:
      operationId: postHealthOperation
      x-google-backend:
        address: https://health-GOOGLE_CLOUD_URL/health
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["POST"]
        allow_headers: ["*"]
        max_age: 3600
    get:
      operationId: getHealthOperation
      x-google-backend:
        address: https://health-GOOGLE_CLOUD_URL/health
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["GET"]
        allow_headers: ["*"]
        max_age: 3600
  /exercise/exercises:
    get:
      operationId: getExercisesOperation
      x-google-backend:
        address: https://exercise-GOOGLE_CLOUD_URL/exercises
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["GET"]
        allow_headers: ["*"]
        max_age: 3600
    post:
      operationId: postExercisesOperation
      x-google-backend:
        address: https://exercise-GOOGLE_CLOUD_URL/exercises
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["GET"]
        allow_headers: ["*"]
        max_age: 3600
  /nutrition/foods:
    post:
      operationId: postFoodsOperation
      x-google-backend:
        address: https://nutrition-GOOGLE_CLOUD_URL/foods
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["POST"]
        allow_headers: ["*"]
        max_age: 3600
    get:
      operationId: getFoodsOperation
      x-google-backend:
        address: https://nutrition-GOOGLE_CLOUD_URL/foods
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["GET"]
        allow_headers: ["*"]
        max_age: 3600
  /chatbot/chat:
    post:
      operationId: chatOperation
      x-google-backend:
        address: https://chatbot-GOOGLE_CLOUD_URL/chat
        path_translation: CONSTANT_ADDRESS
      responses:
        "200":
          description: A successful response
      x-google-cross-origin:
        allow_origin: ["*"]
        allow_methods: ["POST"]
        allow_headers: ["*"]
        max_age: 3600
